main:main.o print_select_bit.o
	gcc -o main main.c print_select_bit.o
main.o:main.c print_select_bit.h
	gcc -c main.c
print_selec_bit.o:print_select_bit.c
	gcc -c print_select_bit.c
clean:
	rm -f *.o

	
