main:main.o make_3.o print_last.o init_array.o
	gcc -o main main.o make_3.o print_last.o init_array.o
main.o:main.c joseph.h
	gcc -c main.c 
make_3.o:make_3.c
	gcc -c make_3.c
print_last.o:print_last.c
	gcc -c print_last.c
init_array.o:init_array.c
	gcc -c init_array.c
clean:
	rm -f *.o
	
	
